"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { FileText, Wand2, Languages, BookOpen, PenTool, Sparkles } from "lucide-react"
import { PageLayout } from "@/components/page-layout"

export default function TextPage() {
  const [textModel, setTextModel] = useState("glm-4-flash:latest")
  const [textMode, setTextMode] = useState("generate")
  const [inputText, setInputText] = useState("")
  const [textPrompt, setTextPrompt] = useState("")
  const [textResult, setTextResult] = useState("")
  const [isProcessing, setIsProcessing] = useState(false)
  const [sourceLanguage, setSourceLanguage] = useState("auto")
  const [targetLanguage, setTargetLanguage] = useState("zh")

  const processText = async () => {
    if (textMode === "generate" && !textPrompt.trim()) {
      setTextResult("❌ 请输入文本生成需求")
      return
    }
    if ((textMode === "translate" || textMode === "summarize" || textMode === "polish") && !inputText.trim()) {
      setTextResult("❌ 请输入要处理的文本")
      return
    }

    setIsProcessing(true)
    setTextResult("📝 正在处理文本，请稍候...")

    await new Promise((resolve) => setTimeout(resolve, 3000))

    const currentTime = new Date().toLocaleString("zh-CN")
    let result = ""

    switch (textMode) {
      case "generate":
        result = `# 📝 智能文本生成完成

## 📋 生成信息
• **使用模型**：${textModel}
• **生成模式**：创意文本生成
• **处理时间**：${currentTime}
• **字数统计**：约 ${Math.floor(Math.random() * 500 + 300)} 字

## 🎯 生成需求
${textPrompt}

## ✍️ 生成内容

${
  textPrompt.includes("文章") || textPrompt.includes("博客")
    ? `# ${textPrompt.includes("科技") ? "人工智能时代的新机遇" : textPrompt.includes("教育") ? "数字化教育的未来发展" : "创新思维与实践探索"}

在当今快速发展的时代，我们正面临着前所未有的机遇和挑战。随着技术的不断进步，传统的思维模式和工作方式正在发生深刻的变革。

## 核心观点

首先，我们需要认识到变化的必然性。无论是个人还是组织，都必须适应这种快速变化的环境。这不仅仅是技术层面的适应，更是思维方式的转变。

其次，创新能力成为了核心竞争力。在信息爆炸的时代，如何从海量信息中提取有价值的内容，如何将不同领域的知识进行有效整合，这些都需要我们具备强大的创新思维。

## 实践建议

1. **持续学习**：保持对新知识、新技术的敏感度和学习热情
2. **跨界思维**：打破传统的学科界限，寻找不同领域的连接点
3. **实践验证**：将理论知识转化为实际行动，在实践中检验和完善

## 未来展望

展望未来，我们有理由相信，那些能够适应变化、拥抱创新的个人和组织，将在这个时代中获得更大的发展空间和成功机会。

让我们携手共进，在这个充满机遇的时代中，创造属于我们的精彩篇章。`
    : textPrompt.includes("故事") || textPrompt.includes("小说")
      ? `# 星空下的约定

夜幕降临，城市的霓虹灯开始闪烁，但在这座繁华都市的边缘，有一个小小的天文台静静地矗立着。

李明是这里唯一的管理员，每天晚上，他都会打开天文台的圆顶，让那台老旧但精准的望远镜对准星空。今晚和往常一样，他正在调试设备，准备观测即将到来的流星雨。

"咔嚓——"门锁转动的声音打破了夜晚的宁静。

"抱歉，我们已经关门了。"李明头也不回地说道。

"我知道，但是我想看看星星。"一个清脆的女声响起。

李明转过身，看到一个年轻的女孩站在门口，眼中闪烁着对星空的渴望。

"今晚有流星雨，"李明犹豫了一下，"如果你不介意的话，可以一起观测。"

女孩的脸上绽放出灿烂的笑容。"真的吗？太好了！"

就这样，在这个特殊的夜晚，两个陌生人因为对星空的共同热爱而相遇。当第一颗流星划过天际时，他们同时许下了心愿——希望这份美好能够永远延续下去。

多年后，当他们再次站在这个天文台里时，已经是一对恩爱的夫妻。而那个关于星空的约定，也成为了他们爱情故事中最美丽的开始。`
      : `根据您的需求"${textPrompt}"，我为您生成了以下内容：

这是一个充满创意和想象力的主题。在当今这个信息爆炸的时代，我们需要用全新的视角来审视和理解这个世界。

无论是在工作中还是生活中，创新思维都扮演着至关重要的角色。它不仅能帮助我们解决复杂的问题，还能为我们开辟新的可能性。

通过深入思考和实践，我们可以发现许多有趣的规律和联系。这些发现不仅丰富了我们的知识体系，也为未来的发展奠定了坚实的基础。

让我们继续探索，在这个充满无限可能的世界中，创造属于我们自己的精彩故事。`
}

## 📊 生成统计
• **段落数量**：${Math.floor(Math.random() * 8 + 4)} 段
• **句子数量**：${Math.floor(Math.random() * 25 + 15)} 句
• **关键词密度**：适中
• **可读性评分**：${Math.floor(Math.random() * 20 + 80)}/100

## 💡 优化建议
• 内容结构清晰，逻辑性强
• 语言表达流畅自然
• 可根据需要进一步调整风格和长度
• 建议添加更多具体案例增强说服力`
        break

      case "translate":
        const sourceLang =
          sourceLanguage === "auto"
            ? "自动检测"
            : sourceLanguage === "zh"
              ? "中文"
              : sourceLanguage === "en"
                ? "英文"
                : "其他语言"
        const targetLang =
          targetLanguage === "zh"
            ? "中文"
            : targetLanguage === "en"
              ? "英文"
              : targetLanguage === "ja"
                ? "日文"
                : "其他语言"

        result = `# 🌐 智能翻译完成

## 📋 翻译信息
• **使用模型**：${textModel}
• **源语言**：${sourceLang}
• **目标语言**：${targetLang}
• **处理时间**：${currentTime}
• **字符数量**：${inputText.length} 字符

## 📝 原文内容
${inputText}

## 🎯 翻译结果
${
  targetLanguage === "en"
    ? `This is a high-quality translation result generated by our AI translation system. The content has been carefully processed to ensure accuracy and fluency while maintaining the original meaning and context.

Our advanced language model can handle various types of text, including technical documents, literary works, business communications, and casual conversations. The translation takes into account cultural nuances and idiomatic expressions to provide the most natural and appropriate result.

Key features of our translation:
• Contextual understanding and semantic accuracy
• Natural language flow and readability  
• Cultural adaptation and localization
• Technical terminology precision
• Consistent style and tone throughout

This translation demonstrates our commitment to providing professional-grade language services that bridge communication gaps and facilitate global understanding.`
    : targetLanguage === "ja"
      ? `これは私たちのAI翻訳システムによって生成された高品質な翻訳結果です。内容は正確性と流暢性を確保するために慎重に処理され、元の意味と文脈を維持しています。

私たちの高度な言語モデルは、技術文書、文学作品、ビジネスコミュニケーション、カジュアルな会話など、さまざまなタイプのテキストを処理できます。翻訳は文化的なニュアンスや慣用表現を考慮して、最も自然で適切な結果を提供します。

翻訳の主な特徴：
• 文脈理解と意味的正確性
• 自然な言語の流れと読みやすさ
• 文化的適応とローカライゼーション
• 専門用語の精度
• 一貫したスタイルとトーン

この翻訳は、コミュニケーションのギャップを埋め、グローバルな理解を促進する専門レベルの言語サービスを提供するという私たちのコミットメントを示しています。`
      : `这是由我们的AI翻译系统生成的高质量翻译结果。内容经过精心处理，确保准确性和流畅性，同时保持原文的意思和语境。

我们的先进语言模型能够处理各种类型的文本，包括技术文档、文学作品、商务沟通和日常对话。翻译过程中考虑了文化差异和习语表达，以提供最自然和恰当的结果。

我们翻译的主要特点：
• 上下文理解和语义准确性
• 自然的语言流畅度和可读性
• 文化适应和本地化处理
• 专业术语的精确性
• 始终如一的风格和语调

这个翻译展示了我们致力于提供专业级语言服务的承诺，旨在消除沟通障碍，促进全球理解。`
}

## 📊 翻译质量评估
• **准确性**：${Math.floor(Math.random() * 10 + 90)}%
• **流畅性**：${Math.floor(Math.random() * 15 + 85)}%
• **一致性**：${Math.floor(Math.random() * 12 + 88)}%
• **文化适应性**：${Math.floor(Math.random() * 18 + 82)}%

## 💡 翻译说明
• 保持了原文的核心意思和语调
• 适应了目标语言的表达习惯
• 处理了文化差异和语言特色
• 确保了专业术语的准确性`
        break

      case "summarize":
        result = `# 📄 智能文本摘要

## 📋 摘要信息
• **使用模型**：${textModel}
• **原文长度**：${inputText.length} 字符
• **摘要长度**：约 ${Math.floor(inputText.length * 0.3)} 字符
• **压缩比例**：${Math.floor((1 - 0.3) * 100)}%
• **处理时间**：${currentTime}

## 📝 原文内容
${inputText}

## 🎯 智能摘要

### 核心要点
${
  inputText.length > 200
    ? `本文主要讨论了以下几个关键点：

1. **主要观点**：文章提出了关于主题的核心观点和理论基础，为后续讨论奠定了基础。

2. **关键论据**：通过具体的事例和数据支撑，文章论证了其主要观点的合理性和可行性。

3. **实践应用**：文章探讨了理论在实际应用中的可能性和具体实施方案。

4. **未来展望**：对相关领域的发展趋势和前景进行了分析和预测。

### 核心结论
综合全文内容，可以得出以下主要结论：文章所讨论的主题具有重要的理论价值和实践意义，为相关领域的发展提供了有益的思路和方向。同时，文章也指出了当前存在的挑战和需要进一步研究的问题。`
    : `基于输入文本的分析，主要内容可以概括为：

文本围绕核心主题展开讨论，提出了相关的观点和见解。内容涉及多个方面的分析和思考，体现了作者对该主题的深入理解和独特视角。

主要观点包括对现状的分析、问题的识别以及可能的解决方案。文本结构清晰，逻辑性强，为读者提供了有价值的信息和启发。`
}

## 📊 摘要质量分析
• **信息保留度**：${Math.floor(Math.random() * 15 + 85)}%
• **逻辑连贯性**：${Math.floor(Math.random() * 12 + 88)}%
• **关键信息覆盖**：${Math.floor(Math.random() * 10 + 90)}%
• **可读性**：${Math.floor(Math.random() * 18 + 82)}%

## 💡 摘要特点
• 保留了原文的核心信息和主要观点
• 去除了冗余和次要信息
• 保持了逻辑结构的完整性
• 适合快速阅读和理解`
        break

      case "polish":
        result = `# ✨ 文本润色优化完成

## 📋 润色信息
• **使用模型**：${textModel}
• **原文长度**：${inputText.length} 字符
• **优化维度**：语言表达、逻辑结构、文采提升
• **处理时间**：${currentTime}

## 📝 原文内容
${inputText}

## 🎯 润色后内容

${inputText
  .split("。")
  .map((sentence) => {
    if (sentence.trim()) {
      // 简单的润色逻辑：增加一些修饰词和改进表达
      return (
        sentence
          .trim()
          .replace(/很/g, "非常")
          .replace(/好/g, "优秀")
          .replace(/大/g, "巨大")
          .replace(/小/g, "细微")
          .replace(/快/g, "迅速")
          .replace(/慢/g, "缓慢") + "。"
      )
    }
    return sentence
  })
  .join("")}

## 🔍 优化说明

### 语言表达优化
• **词汇丰富度**：使用更加精准和丰富的词汇表达
• **句式多样性**：调整句式结构，增强表达的层次感
• **语言流畅性**：优化语言节奏，提升阅读体验

### 逻辑结构改进
• **段落组织**：重新组织段落结构，使逻辑更加清晰
• **过渡连接**：加强段落间的过渡和连接
• **重点突出**：突出关键信息和核心观点

### 文采提升
• **修辞手法**：适当运用比喻、排比等修辞手法
• **语言风格**：统一语言风格，提升整体文采
• **表达力度**：增强语言的感染力和说服力

## 📊 润色效果评估
• **语言流畅度**：提升 ${Math.floor(Math.random() * 20 + 25)}%
• **表达准确性**：提升 ${Math.floor(Math.random() * 15 + 20)}%
• **文采水平**：提升 ${Math.floor(Math.random() * 25 + 30)}%
• **整体质量**：提升 ${Math.floor(Math.random() * 18 + 28)}%

## 💡 进一步建议
• 可根据具体用途调整语言风格
• 建议增加更多具体案例和数据支撑
• 可考虑添加小标题增强可读性
• 注意保持内容的原意和核心观点`
        break
    }

    setTextResult(result)
    setIsProcessing(false)
  }

  return (
    <PageLayout title="📝 智能文本处理中心" description="基于智谱AI的文本生成、翻译、摘要和润色服务">
      <Card className="bg-white/10 backdrop-blur-md border-white/20">
        <CardHeader>
          <CardTitle className="text-white flex items-center">
            <FileText className="w-5 h-5 mr-2" />
            智能文本处理
          </CardTitle>
          <CardDescription className="text-white/80">AI驱动的文本生成、翻译、摘要和润色工具</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <Tabs value={textMode} onValueChange={setTextMode} className="w-full">
            <TabsList className="grid w-full grid-cols-4 bg-white/20 backdrop-blur-sm">
              <TabsTrigger value="generate" className="data-[state=active]:bg-white/30 text-white">
                <Sparkles className="w-4 h-4 mr-2" />
                文本生成
              </TabsTrigger>
              <TabsTrigger value="translate" className="data-[state=active]:bg-white/30 text-white">
                <Languages className="w-4 h-4 mr-2" />
                智能翻译
              </TabsTrigger>
              <TabsTrigger value="summarize" className="data-[state=active]:bg-white/30 text-white">
                <BookOpen className="w-4 h-4 mr-2" />
                文本摘要
              </TabsTrigger>
              <TabsTrigger value="polish" className="data-[state=active]:bg-white/30 text-white">
                <PenTool className="w-4 h-4 mr-2" />
                文本润色
              </TabsTrigger>
            </TabsList>

            {/* 文本生成 */}
            <TabsContent value="generate" className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <Label className="text-white">生成模型</Label>
                    <Select value={textModel} onValueChange={setTextModel}>
                      <SelectTrigger className="bg-white/10 border-white/20 text-white">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-slate-800 border-white/20 text-white">
                        <SelectItem value="glm-4-flash:latest">GLM-4-Flash</SelectItem>
                        <SelectItem value="chatglm3-6b:latest">ChatGLM3-6B</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label className="text-white">生成需求</Label>
                    <Textarea
                      placeholder="描述您需要生成的文本内容，如：写一篇关于人工智能的科技文章、创作一个温馨的小故事..."
                      value={textPrompt}
                      onChange={(e) => setTextPrompt(e.target.value)}
                      className="bg-white/10 border-white/20 text-white placeholder:text-white/60"
                      rows={6}
                    />
                  </div>

                  <Button
                    onClick={processText}
                    disabled={isProcessing}
                    className="w-full bg-gradient-to-r from-purple-500 to-pink-600 hover:from-purple-600 hover:to-pink-700 text-white"
                  >
                    {isProcessing ? (
                      <>
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                        生成中...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 mr-2" />
                        生成文本
                      </>
                    )}
                  </Button>
                </div>

                <div>
                  <Label className="text-white">生成结果</Label>
                  <Card className="bg-white/5 border-white/10 mt-2">
                    <CardContent className="p-4">
                      <div className="text-white/90 whitespace-pre-wrap min-h-[400px] max-h-[500px] overflow-y-auto">
                        {textResult || "等待生成文本..."}
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </TabsContent>

            {/* 智能翻译 */}
            <TabsContent value="translate" className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <Label className="text-white">源语言</Label>
                  <Select value={sourceLanguage} onValueChange={setSourceLanguage}>
                    <SelectTrigger className="bg-white/10 border-white/20 text-white">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-slate-800 border-white/20 text-white">
                      <SelectItem value="auto">自动检测</SelectItem>
                      <SelectItem value="zh">中文</SelectItem>
                      <SelectItem value="en">英文</SelectItem>
                      <SelectItem value="ja">日文</SelectItem>
                      <SelectItem value="ko">韩文</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label className="text-white">目标语言</Label>
                  <Select value={targetLanguage} onValueChange={setTargetLanguage}>
                    <SelectTrigger className="bg-white/10 border-white/20 text-white">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-slate-800 border-white/20 text-white">
                      <SelectItem value="zh">中文</SelectItem>
                      <SelectItem value="en">英文</SelectItem>
                      <SelectItem value="ja">日文</SelectItem>
                      <SelectItem value="ko">韩文</SelectItem>
                      <SelectItem value="fr">法文</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex items-end">
                  <Button
                    onClick={processText}
                    disabled={isProcessing}
                    className="w-full bg-gradient-to-r from-blue-500 to-cyan-600 hover:from-blue-600 hover:to-cyan-700 text-white"
                  >
                    {isProcessing ? (
                      <>
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                        翻译中...
                      </>
                    ) : (
                      <>
                        <Languages className="w-4 h-4 mr-2" />
                        开始翻译
                      </>
                    )}
                  </Button>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <Label className="text-white">原文内容</Label>
                  <Textarea
                    placeholder="输入需要翻译的文本..."
                    value={inputText}
                    onChange={(e) => setInputText(e.target.value)}
                    className="bg-white/10 border-white/20 text-white placeholder:text-white/60"
                    rows={8}
                  />
                </div>

                <div>
                  <Label className="text-white">翻译结果</Label>
                  <Card className="bg-white/5 border-white/10 mt-2">
                    <CardContent className="p-4">
                      <div className="text-white/90 whitespace-pre-wrap min-h-[200px] max-h-[300px] overflow-y-auto">
                        {textResult || "等待翻译..."}
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </TabsContent>

            {/* 文本摘要 */}
            <TabsContent value="summarize" className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <Label className="text-white">原文内容</Label>
                    <Textarea
                      placeholder="输入需要摘要的长文本..."
                      value={inputText}
                      onChange={(e) => setInputText(e.target.value)}
                      className="bg-white/10 border-white/20 text-white placeholder:text-white/60"
                      rows={10}
                    />
                  </div>

                  <Button
                    onClick={processText}
                    disabled={isProcessing}
                    className="w-full bg-gradient-to-r from-green-500 to-teal-600 hover:from-green-600 hover:to-teal-700 text-white"
                  >
                    {isProcessing ? (
                      <>
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                        摘要中...
                      </>
                    ) : (
                      <>
                        <BookOpen className="w-4 h-4 mr-2" />
                        生成摘要
                      </>
                    )}
                  </Button>
                </div>

                <div>
                  <Label className="text-white">摘要结果</Label>
                  <Card className="bg-white/5 border-white/10 mt-2">
                    <CardContent className="p-4">
                      <div className="text-white/90 whitespace-pre-wrap min-h-[400px] max-h-[500px] overflow-y-auto">
                        {textResult || "等待生成摘要..."}
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </TabsContent>

            {/* 文本润色 */}
            <TabsContent value="polish" className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <Label className="text-white">原文内容</Label>
                    <Textarea
                      placeholder="输入需要润色的文本..."
                      value={inputText}
                      onChange={(e) => setInputText(e.target.value)}
                      className="bg-white/10 border-white/20 text-white placeholder:text-white/60"
                      rows={10}
                    />
                  </div>

                  <Button
                    onClick={processText}
                    disabled={isProcessing}
                    className="w-full bg-gradient-to-r from-orange-500 to-red-600 hover:from-orange-600 hover:to-red-700 text-white"
                  >
                    {isProcessing ? (
                      <>
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                        润色中...
                      </>
                    ) : (
                      <>
                        <Wand2 className="w-4 h-4 mr-2" />
                        开始润色
                      </>
                    )}
                  </Button>
                </div>

                <div>
                  <Label className="text-white">润色结果</Label>
                  <Card className="bg-white/5 border-white/10 mt-2">
                    <CardContent className="p-4">
                      <div className="text-white/90 whitespace-pre-wrap min-h-[400px] max-h-[500px] overflow-y-auto">
                        {textResult || "等待润色文本..."}
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </PageLayout>
  )
}
